name: Laravel 

on:
  schedule:
  - cron:  '30 6 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Nginx-php81-laravel9-AMD64:
    runs-on: macos-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     php-version: ['8.1', '8.0']
    #     back: ['nginx', 'apache']
    steps:
    - uses: actions/checkout@v2
    - name: Multipass Installation
      run: curl https://raw.githubusercontent.com/nabad600/multipass-script/master/install.sh | sh
    - name: Multipass version 
      run: multipass version
    - name: Multipass Hostname
      run: multipass exec deck-app hostname
    - name: Multipass Check IP
      run: multipass info deck-app | grep IPv4 | awk '{print $2}'
    - name: Multipass docker
      run: multipass exec deck-app docker ps
    - name: Remote access docker
      run: echo 'alias docker="multipass exec deck-app docker"' >> ~/.zshrc && source ~/.zshrc
    - name: Remote access docker
      run: echo "export DOCKER_HOST=tcp://`multipass info deck-app | grep IPv4 | awk '{print $2}'`:2376" >> ~/.bashrc && source ~/.bashrc
    - name: Local docker test
      run: |
        curl `multipass info deck-app | grep IPv4 | awk '{print $2}'`:2376
        multipass exec deck-app sudo apt install docker-compose