name: Laravel 

on:
  schedule:
  - cron:  '30 6 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Nginx-php81-laravel9-AMD64:
    runs-on: macos-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     php-version: ['8.1', '8.0']
    #     back: ['nginx', 'apache']
    steps:
    - uses: actions/checkout@v2
    - name: Multipass Installation
      run: curl https://raw.githubusercontent.com/nabad600/multipass-script/master/install.sh | sh
    - name: Multipass version 
      run: multipass version
    - name: Multipass 
      run: multipass exec deck-app -- bash -c docker ps
  