name: Laravel 

on:
  schedule:
  - cron:  '30 6 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Nginx-php81-laravel9-AMD64:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     php-version: ['8.1', '8.0']
    #     back: ['nginx', 'apache']
    steps:
    - uses: actions/checkout@v2
    # - name: Deleted container 
    #   run: |
    #     docker stop $(docker ps -a -q)
    #     echo "y" | docker system prune -a
    #     sudo rm -rf /tmp/lara
    - name: Multipass installation
      run: curl https://raw.githubusercontent.com/nabad600/multipass-script/master/install.sh | sh
  